package com.example.dataprivacy.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity // Maps the class to the scan_results table
public class ScanResult {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that id, is the primary key, and its value will be
														// autogenerated
	private Long id;

	private String fileName;

	@Column(name = "scan_results", columnDefinition = "JSONB")
	private String scanResults;

	private LocalDateTime scannedAt; // Local DateTime represents the scaned_at column.

	// Getters and Setters
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getScanResults() {
		return scanResults;
	}

	public void setScanResults(String scanResults) {
		this.scanResults = scanResults;
	}

	public LocalDateTime getScannedAt() {
		return scannedAt;
	}

	public void setScannedAt(LocalDateTime scannedAt) {
		this.scannedAt = scannedAt;
	}

}
